//implementation of IndexMapBaseTest

#include<cppunit/extensions/HelperMacros.h>

#include "AddOperatorTest.hpp"


CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<UInt32>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Int32>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<UInt64>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Int64>);

CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Float32>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Float64>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Float128>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Complex32>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Complex64>);
CPPUNIT_TEST_SUITE_REGISTRATION(AddOperatorTest<Complex128>);



