//implementation of IndexMapBaseTest

#include<cppunit/extensions/HelperMacros.h>

#include "DivOperatorTest.hpp"


CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<UInt32>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Int32>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<UInt64>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Int64>);

CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Float32>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Float64>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Float128>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Complex32>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Complex64>);
CPPUNIT_TEST_SUITE_REGISTRATION(DivOperatorTest<Complex128>);



