//implementation of IndexMapBaseTest

#include<cppunit/extensions/HelperMacros.h>

#include "MultOperatorTest.hpp"


CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<UInt32>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Int32>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<UInt64>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Int64>);

CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Float32>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Float64>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Float128>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Complex32>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Complex64>);
CPPUNIT_TEST_SUITE_REGISTRATION(MultOperatorTest<Complex128>);



