//implementation for the Buffer test

#include "RBufferTest.hpp"


CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Int8>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<UInt16>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<UInt32>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Int32>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<UInt64>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Int64>);

CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Float32>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Float64>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Float128>);

CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Complex32>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Complex64>);
CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Complex128>);

CPPUNIT_TEST_SUITE_REGISTRATION(RBufferTest<Binary>);
