//implementation for the Buffer test

#include "RefBufferTest.hpp"


CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Int8>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<UInt16>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<UInt32>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Int32>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<UInt64>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Int64>);

CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Float32>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Float64>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Float128>);

CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Complex32>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Complex64>);
CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Complex128>);

CPPUNIT_TEST_SUITE_REGISTRATION(RefBufferTest<Binary>);
