//implementation of the unit tests for arrays

#include<cppunit/extensions/HelperMacros.h>

#include <iostream>
#include <boost/shared_ptr.hpp>

#include "SArrayTest.hpp"

using namespace pni::utils;

#define STATICARRAY_TEST_REGISTRATION(T)\
static CPPUNIT_NS::AutoRegisterSuite< SArrayTest<T> >  \
             CPPUNIT_MAKE_UNIQUE_NAME(autoRegisterRegistry__ );

STATICARRAY_TEST_REGISTRATION(UInt8);
STATICARRAY_TEST_REGISTRATION(Int8);
STATICARRAY_TEST_REGISTRATION(UInt16);
STATICARRAY_TEST_REGISTRATION(Int16);
STATICARRAY_TEST_REGISTRATION(UInt32);
STATICARRAY_TEST_REGISTRATION(Int32);
STATICARRAY_TEST_REGISTRATION(UInt64);
STATICARRAY_TEST_REGISTRATION(Int64);

STATICARRAY_TEST_REGISTRATION(Float32);
STATICARRAY_TEST_REGISTRATION(Float64);
STATICARRAY_TEST_REGISTRATION(Float128);

STATICARRAY_TEST_REGISTRATION(Complex32);
STATICARRAY_TEST_REGISTRATION(Complex64);
STATICARRAY_TEST_REGISTRATION(Complex128);


