//implementation for the Buffer test

#include "SBufferTest.hpp"


CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Int8>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<UInt16>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<UInt32>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Int32>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<UInt64>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Int64>);

CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Float32>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Float64>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Float128>);

CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Complex32>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Complex64>);
CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Complex128>);

CPPUNIT_TEST_SUITE_REGISTRATION(SBufferTest<Binary>);
