Import("build_env")

test_env = build_env.Clone()

test_env.Append(LIBPATH=["../src/"])
test_env.Append(LIBS=["pniutils","cppunit"])
test_env.Append(CPPPATH=["../src/"])

sources_list = ["pniutilstest.cpp"]
sources_list.extend(["libpniutils_datavalue.cpp"])
sources_list.extend(["libpniutils_scalar.cpp"])
sources_list.extend(["libpniutils_buffer.cpp"])
sources_list.extend(["libpniutils_array.cpp"])
sources_list.extend(["libpniutils_arrayshape.cpp"])

pniutils_test = test_env.Program("pniutilstest",sources_list)
cbfreader_test = test_env.Program("cbf_reader_test",["cbf_reader_test.cpp"])
test_env.Alias("test",[pniutils_test,cbfreader_test])
test_env.Alias("all",[pniutils_test,cbfreader_test])
