//implementation for the Buffer test

#include "StaticBufferTest.hpp"


CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Int8>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<UInt16>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<UInt32>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Int32>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<UInt64>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Int64>);

CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Float32>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Float64>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Float128>);

CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Complex32>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Complex64>);
CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Complex128>);

CPPUNIT_TEST_SUITE_REGISTRATION(StaticBufferTest<Binary>);
