//implementation of IndexMapBaseTest

#include<cppunit/extensions/HelperMacros.h>

#include "SubOperatorTest.hpp"


CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<UInt8>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Int16>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<UInt32>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Int32>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<UInt64>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Int64>);

CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Float32>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Float64>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Float128>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Complex32>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Complex64>);
CPPUNIT_TEST_SUITE_REGISTRATION(SubOperatorTest<Complex128>);



