import os

env = Environment()
env.AppendUnique(CXXFLAGS=["-std=c++11","-pedantic","-Wall","-Wextra"])
env["ENV"]["PKG_CONFIG_PATH"]=os.environ["PKG_CONFIG_PATH"]
env.ParseConfig('pkg-config --cflags --libs pnicore')
env.Program('array_arithmetic1.cpp')
env.Program('array_arithmetic2.cpp')
env.Program('array_arithmetic3.cpp')
env.Program('array_create.cpp')
env.Program('array_inquery.cpp')
env.Program('array_linear_access.cpp')
env.Program('array_multiindex.cpp')
env.Program('array_stl.cpp')
env.Program('array_view_container.cpp')
env.Program('array_view.cpp')
env.Program('copy_file.cpp')
env.Program('type_erasure1.cpp')
