import os.path as path
import subprocess

Import("build_env")


api_doc_dir = "api-doc"
api_doc_html_dir = "html"

#need to figure out which version of doxygen is installed

doxygen_output = subprocess.Popen(["doxygen",""], 
                               stdout=subprocess.PIPE).communicate()[0]
#split output string
version_line = doxygen_output.split("\n")[0]
version_string = version_line.split(" ")[-1]
doxygen_version = int(version_string.replace(".",""))

print doxygen_version

doxyfile_extension = ["DOXYFILE_ENCODING      = UTF-8",
                      "TYPEDEF_HIDES_STRUCT   = NO",
                      "SYMBOL_CACHE_SIZE      = 0",
                      "EXTRACT_ANON_NSPACES   = NO",
                      "FORCE_LOCAL_INCLUDES   = NO",
                      "SORT_MEMBERS_CTORS_1ST = NO",
                      "SORT_GROUP_NAMES       = NO",
                      "SHOW_FILES             = YES",
                      "SHOW_NAMESPACES        = YES",
                      "INPUT_ENCODING         = UTF-8",
                      "EXCLUDE_SYMBOLS        = pni::utils::ArrayType<T>,pni::utils::PNITypeInfo<Int8>",
                      "HTML_COLORSTYLE_HUE    = 220",
                      "HTML_COLORSTYLE_SAT    = 100",
                      "HTML_COLORSTYLE_GAMMA  = 80",
                      "HTML_TIMESTAMP         = YES",
                      "HTML_DYNAMIC_SECTIONS  = NO",
                      "GENERATE_DOCSET        = NO",
                      "DOCSET_FEEDNAME        = 'Documentation for ${'$LIBPREFIX'+'$LIBNAME'+'-'+'$VERSION'}'",
                      "DOCSET_BUNDLE_ID       = org.doxygen.${'$LIBPREFIX'+'$LIBNAME'+'-'+'$VERSION'}",
                      "DOCSET_PUBLISHER_ID    = org.doxygen.DESY",
                      "DOCSET_PUBLISHER_NAME  = DESY",
                      "CHM_INDEX_ENCODING     =",
                      "GENERATE_QHP           = NO",
                      "GENERATE_ECLIPSEHELP   = YES",
                      "USE_INLINE_TREES       = YES",
                      "EXT_LINKS_IN_WINDOW    = NO",
                      "FORMULA_FONTSIZE       = 10",
                      "FORMULA_TRANSPARENT    = YES",
                      "SERVER_BASED_SEARCH    = NO",
                      "LATEX_SOURCE_CODE      = NO",
                      "MSCGEN_PATH            =",
                      "DOT_NUM_THREADS        = 0",
                      "DOT_FONTNAME           = FreeSans.ttf",
                      "DOT_FONTSIZE           = 10",
                      "DOT_FONTPATH           =",
                      "DOT_GRAPH_MAX_NODES    = 50",
                      "USE_MATHJAX = YES",
                      "WARN_FORMAT            = '$file:$line: $text'"
                     ] 

doxyfile_source = [
           "NO_API_DOC           = YES",
           "PROJECT_NAME           = ${LIBPREFIX}${LIBNAME}",
           "PROJECT_NUMBER         =",
           "OUTPUT_DIRECTORY       = %s" %api_doc_dir,
           "CREATE_SUBDIRS         = NO",
           "OUTPUT_LANGUAGE        = English",
           "BRIEF_MEMBER_DESC      = YES",
           "REPEAT_BRIEF           = YES",
           "ALWAYS_DETAILED_SEC    = NO",
           "INLINE_INHERITED_MEMB  = NO",
           "FULL_PATH_NAMES        = NO",
           "STRIP_FROM_PATH        =",
           "STRIP_FROM_INC_PATH    =",
           "SHORT_NAMES            = NO",
           "JAVADOC_AUTOBRIEF      = NO",
           "MULTILINE_CPP_IS_BRIEF = NO",
           "INHERIT_DOCS           = YES",
           "SEPARATE_MEMBER_PAGES  = NO",
           "TAB_SIZE               = 8",
           "ALIASES                =",
           "OPTIMIZE_OUTPUT_FOR_C  = YES",
           "OPTIMIZE_OUTPUT_JAVA   = NO",
           "BUILTIN_STL_SUPPORT    = YES",
           "DISTRIBUTE_GROUP_DOC   = NO",
           "SUBGROUPING            = YES",
            #---------------------------------------------------------------------------
            # Build related configuration options
            #---------------------------------------------------------------------------
            "EXTRACT_ALL            = NO",
            "EXTRACT_PRIVATE        = NO",
            "EXTRACT_STATIC         = NO",
            "EXTRACT_LOCAL_CLASSES  = YES",
            "EXTRACT_LOCAL_METHODS  = NO",
            "HIDE_UNDOC_MEMBERS     = NO",
            "HIDE_UNDOC_CLASSES     = NO",
            "HIDE_FRIEND_COMPOUNDS  = NO",
            "HIDE_IN_BODY_DOCS      = NO",
            "INTERNAL_DOCS          = NO",
            "CASE_SENSE_NAMES       = YES",
            "HIDE_SCOPE_NAMES       = NO",
            "SHOW_INCLUDE_FILES     = YES",
            "INLINE_INFO            = YES",
            "SORT_MEMBER_DOCS       = YES",
            "SORT_BRIEF_DOCS        = NO",
            "SORT_BY_SCOPE_NAME     = NO",
            "GENERATE_TODOLIST      = YES",
            "GENERATE_TESTLIST      = YES",
            "GENERATE_BUGLIST       = YES",
            "GENERATE_DEPRECATEDLIST= YES",
            "ENABLED_SECTIONS       =",
            "MAX_INITIALIZER_LINES  = 30",
            "SHOW_USED_FILES        = YES",
            "SHOW_DIRECTORIES       = NO",
            #---------------------------------------------------------------------------
            # configuration options related to warning and progress messages
            #---------------------------------------------------------------------------
            "QUIET                  = NO",
            "WARNINGS               = YES",
            "WARN_IF_UNDOCUMENTED   = YES",
            "WARN_IF_DOC_ERROR      = YES",
            "WARN_NO_PARAMDOC       = NO",
            "WARN_LOGFILE           =",
            #---------------------------------------------------------------------------
            # configuration options related to the input files
            #---------------------------------------------------------------------------
            "INPUT                  = ../src/",
            "FILE_PATTERNS          =",
            "RECURSIVE              = YES",
            "EXCLUDE                =",
            "EXCLUDE_SYMLINKS       = NO",
            "EXCLUDE_PATTERNS       =",
            "EXAMPLE_PATH           =",
            "EXAMPLE_PATTERNS       =",
            "EXAMPLE_RECURSIVE      = NO",
            "IMAGE_PATH             =",
            "INPUT_FILTER           =",
            "FILTER_PATTERNS        =",
            "FILTER_SOURCE_FILES    = NO",
            #---------------------------------------------------------------------------
            # configuration options related to source browsing
            #---------------------------------------------------------------------------
            "SOURCE_BROWSER         = NO",
            "INLINE_SOURCES         = NO",
            "STRIP_CODE_COMMENTS    = YES",
            "REFERENCED_BY_RELATION = NO",
            "REFERENCES_RELATION    = NO",
            "REFERENCES_LINK_SOURCE = YES",
            "USE_HTAGS              = NO",
            "VERBATIM_HEADERS       = YES",
            #---------------------------------------------------------------------------
            # configuration options related to the alphabetical class index
            #---------------------------------------------------------------------------
            "ALPHABETICAL_INDEX     = YES",
            "COLS_IN_ALPHA_INDEX    = 5",
            "IGNORE_PREFIX          =", 
            #---------------------------------------------------------------------------
            # configuration options related to the HTML output
            #---------------------------------------------------------------------------
            "GENERATE_HTML          = YES",
            "HTML_OUTPUT            = %s" %api_doc_html_dir,
            "HTML_FILE_EXTENSION    = .html",
            "HTML_HEADER            =",
            "HTML_FOOTER            =",
            "HTML_STYLESHEET        =",
            "HTML_ALIGN_MEMBERS     = YES",
            "GENERATE_TREEVIEW = YES",
            "GENERATE_HTMLHELP      = YES",
            "CHM_FILE               = ${'$LIBPREFIX'+'$LIBNAME'+'-'+'$VERSION'}.chm", 
            "HHC_LOCATION           =",
            "GENERATE_CHI           = NO",
            "BINARY_TOC             = NO",
            "TOC_EXPAND             = NO",
            "DISABLE_INDEX          = NO",
            "ENUM_VALUES_PER_LINE   = 4",
            "GENERATE_TREEVIEW      = YES",
            "TREEVIEW_WIDTH         = 250",
            "SEARCHENGINE           = YES",
            #---------------------------------------------------------------------------
            # Configuration options related to the preprocessor
            #---------------------------------------------------------------------------
            "ENABLE_PREPROCESSING   = YES",
            "MACRO_EXPANSION        = NO",
            "EXPAND_ONLY_PREDEF     = NO",
            "SEARCH_INCLUDES        = YES",
            "INCLUDE_PATH           =",
            "INCLUDE_FILE_PATTERNS  =",
            "PREDEFINED             =",
            "EXPAND_AS_DEFINED      =",
            "SKIP_FUNCTION_MACROS   = YES",
            #---------------------------------------------------------------------------
            # Configuration::additions related to external references
            #---------------------------------------------------------------------------
            "TAGFILES               =",
            "GENERATE_TAGFILE       =",
            "ALLEXTERNALS           = NO",
            "EXTERNAL_GROUPS        = YES",
            "PERL_PATH              = /usr/bin/perl",
            #---------------------------------------------------------------------------
            # Configuration options related to the dot tool
            #---------------------------------------------------------------------------
            "CLASS_DIAGRAMS         = YES",
            "HIDE_UNDOC_RELATIONS   = YES",
            "HAVE_DOT               = NO",
            "CLASS_GRAPH            = YES",
            "COLLABORATION_GRAPH    = YES",
            "GROUP_GRAPHS           = YES",
            "UML_LOOK               = NO",
            "TEMPLATE_RELATIONS     = NO",
            "INCLUDE_GRAPH          = YES",
            "INCLUDED_BY_GRAPH      = YES",
            "CALL_GRAPH             = NO",
            "CALLER_GRAPH           = NO",
            "GRAPHICAL_HIERARCHY    = YES",
            "DIRECTORY_GRAPH        = YES",
            "DOT_IMAGE_FORMAT       = png",
            "DOT_PATH               =",
            "DOTFILE_DIRS           =",
            "MAX_DOT_GRAPH_DEPTH    = 0",
            "DOT_TRANSPARENT        = NO",
            "DOT_MULTI_TARGETS      = YES",
            "GENERATE_LEGEND        = YES",
            "DOT_CLEANUP            = YES"
            ]

if doxygen_version > 160:
    doxyfile_source.extend(doxyfile_extension)

doxyfile = build_env.Textfile("Doxyfile",doxyfile_source,TEXTFILESUFFIX="")
            
doxygen_api_doc = build_env.Command(["api-doc/html"],
                                    doxyfile,
                                    "cd doc; doxygen $SOURCE.file")

Clean(doxygen_api_doc,"api-doc")
admin_guide = SConscript("admin-guide/SConscript")
users_guide = SConscript("users-guide/SConscript")



build_env.Alias("doc",[doxygen_api_doc,admin_guide,users_guide])
     
api_html_doc_install = build_env.Install("${DOCDIR}/api","api-doc/html")
admin_guide_install = build_env.Install("${DOCDIR}",admin_guide)
users_guide_install = build_env.Install("${DOCDIR}",users_guide)

build_env.Alias("all",[doxygen_api_doc,admin_guide,users_guide])
build_env.Alias("install",[api_html_doc_install,admin_guide_install,
                           users_guide_install])


