Document: libpniutils
Title: Debian libpniutils Manual
Author: Eugen Wintersberger
Abstract: This manual describes what libpniutils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

#Format: postscript
#Files: /usr/share/doc/libpniutils/libpniutils.ps.gz

#Format: text
#Files: /usr/share/doc/libpniutils/libpniutils.text.gz

Format: HTML
Index: /usr/share/doc/libpniutils/API/html/index.html
Files: /usr/share/doc/libpniutils/API/html/*.html
