Import("build_env")


debian_dict = {"@SOURCE@":"$LIBPREFIX$LIBNAME","@MAINTAINER@":"$MAINTAINER",
               "@MAINTAINER_MAIL@":"$MAINTAINER_MAIL",
               "@PKGNAME@":"$PKGNAME","@VERSION@":"$VERSION",
               "@LIBINSTPATH@":"$LIBINSTPATH","@INCINSTPATH@":"$INCINSTPATH",
               "@DOCDIR@":"$DOCDIR"}
               
#-------------------------create control file-----------------------------------
                  
control_file = build_env.Substfile(["control.in"],SUBST_DICT=debian_dict)
build_env.NoClean(control_file)

changelog_source = [ "libpniutils (${VERSION}) unstable; urgency=low",
                     "",
                     "  * Initial Release.",
                     " -- ${MAINTAINER} <${MAINTAINER_MAIL}>  Tue, 24 May 2011 11:15:08 +0200",
                     ""]
changelog_file = build_env.Textfile(target="changelog",source=changelog_source,
                                    TEXTFILESUFFIX="")                                  
build_env.NoClean(changelog_file)

rules_file = build_env.Substfile(["rules.in"])
build_env.NoClean(rules_file)

compat_file = build_env.Substfile(["compat.in"])
build_env.NoClean(compat_file)

lib_pkg_dirs = build_env.Substfile(target="${PKGNAME}",
                source=["libpniutils.dirs.in"],SUBST_DICT=debian_dict,
                SUBSTFILESUFFIX=".dirs")
build_env.NoClean(lib_pkg_dirs)

lib_pkg_install = build_env.Substfile(target="${PKGNAME}",
                  source=["libpniutils.install.in"],SUBST_DICT=debian_dict,
                  SUBSTFILESUFFIX=".install")
build_env.NoClean(lib_pkg_install)

dev_pkg_dirs = build_env.Substfile(target="${PKGNAME}-dev",
               source = ["libpniutils-dev.dirs.in"],
               SUBST_DICT=debian_dict,SUBSTFILESUFFIX=".dirs")
build_env.NoClean(dev_pkg_dirs)

dev_pkg_install = build_env.Substfile(target="${PKGNAMEROOT}-dev",
                  source=["libpniutils-dev.install.in"],SUBST_DICT=debian_dict,
                  SUBSTFILESUFFIX=".install")
build_env.NoClean(dev_pkg_install)                                                               

doc_pkg_dirs = build_env.Substfile(target="${PKGNAME}-doc",
                                  source=["libpniutils-doc.dirs.in"],
                                  SUBST_DICT=debian_dict,SUBSTFILESUFFIX=".dirs")
build_env.NoClean(doc_pkg_dirs)                                                                      
doc_pkg_install = build_env.Substfile(target="${PKGNAME}-doc",
                                     source=["libpniutils-doc.install.in"],
                                     SUBST_DICT=debian_dict,
                                     SUBSTFILESUFFIX=".install")
build_env.NoClean(doc_pkg_install)

build_env.Alias("debian",[control_file,compat_file,lib_pkg_dirs,lib_pkg_install,
                          dev_pkg_dirs,dev_pkg_install,
                          doc_pkg_dirs,doc_pkg_install,changelog_file,rules_file])
