from distutils import sysconfig
Import("python_build_env")


python_build_env.Append(LIBS=["pniutils"])
python_build_env.Append(LIBPATH=["../src"])

python_build_env.Append(LIBS=["boost_python","boost_python-py27"])
python_build_env.Append(CPPPATH=[sysconfig.get_python_inc()])

python_sources = ["DataObject.cpp"]

module = python_build_env.SharedLibrary("pniutils",python_sources,SHLIBPREFIX="")
python_build_env.Alias("all",[module])