from distutils import sysconfig
Import("python_build_env")


python_build_env.Prepend(LIBS=["pniutils"])
python_build_env.Prepend(LIBPATH=["../src"])

python_version = sysconfig.get_python_version()
python_version = python_version.replace(".","")

python_build_env.Append(LIBS=["boost_python","boost_python-py"+python_version])
python_build_env.Append(CPPPATH=[sysconfig.get_python_inc()])

python_sources = ["NumericObject.cpp","DataObject.cpp","Index.cpp",
                  "Shape.cpp","Buffer.cpp","Scalar.cpp","Array.cpp",
                  "BufferObject.cpp","ArrayObject.cpp",
                  "pniutils.cpp"]

module = python_build_env.SharedLibrary("pni/utils/pniutils",python_sources,SHLIBPREFIX="")
python_build_env.Alias("python",[module])

