import os.path as path

Import("build_env")


sources = ["Reader.cpp","CBFReader.cpp","strutils.cpp","CIFBinHeader.cpp",
           "PCIFBinHeader.cpp","CBFBinStreamReader.cpp","TIFFReader.cpp","TIFFFile.cpp",
           "TIFFIDF.cpp"]

sobjs = build_env.SharedObject(sources)
aobjs = build_env.StaticObject(sources)

hdr_inst_path = path.join(build_env["ENV"]["INSTALL_PREFIX"],"include/pni/utils/io")
incpniutils_inst = build_env.Install(hdr_inst_path,Glob("*.hpp"))
build_env.Alias("install",[incpniutils_inst])

Return("sobjs aobjs")