Import("build_env")

sources = ["cbfreader.cpp","strutils.cpp","cifbinheader.cpp",
           "pcifbinheader.cpp","cbfbinstreamreader.cpp"]

objects = build_env.SharedObject(sources)
Return("objects")