check_type_size(uint8_t UINT8_SIZE)
if(NOT ${UINT8_SIZE} EQUAL 1)
    message(FATAL_ERROR "uint8_t size is not 1Byte!")
else()
    message(STATUS "uint8_t size is ${UINT8_SIZE} byte")
endif()

check_type_size(int8_t INT8_SIZE)
if(NOT ${INT8_SIZE} EQUAL 1)
    message(FATAL_ERROR "int8_t size is not 1Byte!")
else()
    message(STATUS "int8_t size is ${INT8_SIZE} byte")
endif()

check_type_size(uint16_t UINT16_SIZE)
if(NOT ${UINT16_SIZE} EQUAL 2)
    message(FATAL_ERROR "uint16_t size is not 2Byte!")
else()
    message(STATUS "uint16_t size is ${UINT16_SIZE} byte")
endif()

check_type_size(int16_t INT16_SIZE)
if(NOT ${INT16_SIZE} EQUAL 2)
    message(FATAL_ERROR "int16_t size is not 2Byte!")
else()
    message(STATUS "int16_t size is ${INT16_SIZE} byte")
endif()

check_type_size(uint32_t UINT32_SIZE)
if(NOT ${UINT32_SIZE} EQUAL 4)
    message(FATAL_ERROR "uint32_t size is not 4Byte!")
else()
    message(STATUS "uint32_t size is ${UINT32_SIZE} byte")
endif()

check_type_size(int32_t INT32_SIZE)
if(NOT ${INT32_SIZE} EQUAL 4)
    message(FATAL_ERROR "int32_t size is not 4Byte!")
else()
    message(STATUS "int32_t size is ${INT32_SIZE} byte")
endif()

check_type_size(uint64_t UINT64_SIZE)
if(NOT ${UINT64_SIZE} EQUAL 8)
    message(FATAL_ERROR "uint64_t size is not 8Byte!")
else()
    message(STATUS "uint64_t size is ${UINT64_SIZE} byte")
endif()

check_type_size(int64_t INT64_SIZE)
if(NOT ${INT64_SIZE} EQUAL 8)
    message(FATAL_ERROR "int64_t size is not 8Byte!")
else()
    message(STATUS "int64_t size is ${INT64_SIZE} byte")
endif()

check_type_size(float FLOAT32_SIZE)
if(NOT ${FLOAT32_SIZE} EQUAL 4)
    message(FATAL_ERROR "float size is not 4Byte!")
else()
    message(STATUS "float size is ${FLOAT32_SIZE} byte")
endif()

check_type_size(double FLOAT64_SIZE)
if(NOT ${FLOAT64_SIZE} EQUAL 8)
    message(FATAL_ERROR "double size is not 8Byte!")
else()
    message(STATUS "double size is ${FLOAT64_SIZE} byte")
endif()

check_type_size("long double" FLOAT128_SIZE)
message(STATUS "long double size is ${FLOAT128_SIZE} bytes")
if((NOT ${FLOAT128_SIZE} EQUAL 16) AND (NOT ${FLOAT128_SIZE} EQUAL 12) 
    AND (NOT ${FLOAT128_SIZE} EQUAL 8))
    message(FATAL_ERROR "long double size is not 16Byte or 12Byte but ${FLOAT128_SIZE}!")
endif()
