import os.path as path
Import("build_env")


#----------------------Building object files------------------------------------
source_list = []
source_list.extend(["Exceptions.cpp","Types.cpp","Slice.cpp","ComplexUtils.cpp","ExceptionUtils.cpp"])
#source_list.extend([ "Shape.cpp", "DataObject.cpp","NumericObject.cpp" ])
               
#build static and shared objects               
shared_objects = build_env.SharedObject(source_list)
static_objects = build_env.StaticObject(source_list)
#(shared_io_objects,static_io_objects) = SConscript("io/SConscript")
#shared_objects.append(shared_io_objects)
#static_objects.append(static_io_objects)

#----------------------Linking libraries----------------------------------------
#link temporary shared library
temp_shared_library = build_env.SharedLibrary("temp",shared_objects,
                      so_version="${SOVERSION}")
#create real target library with proper permissions                                                                     
shared_library = build_env.Command("${LIBFULLNAME}",temp_shared_library[0],
                 [  Move("$TARGET","$SOURCE"), Chmod("$TARGET",0644)])

#creating links to the target library according to GNU naming convention
shared_library_link = build_env.Command("${LIBLINKNAME}",shared_library,
                     "cd src/; ln -sf ${SOURCE.file} ${TARGET.file}")
shared_library_so = build_env.Command("${LIBSONAME}",shared_library,
                    "cd src/; ln -sf ${SOURCE.file} ${TARGET.file}")
                                 
#link static library
static_library = build_env.StaticLibrary("${LIBNAME}",static_objects)


#---------------------build the pkg-config file---------------------------------              
pkg_config_file = build_env.Substfile(target="${LIBNAME}",source=["pkgconf.in"],
                  SUBST_DICT={"@PREFIX@":"${PREFIX}","@LIBNAME@":"${LIBNAME}",
                  "@INCDIR@":build_env["INCDIR"].replace("/pni/utils",""),
                  "@VERSION@":"${VERSION}","@BOOSTINCDIR@":"${BOOSTINCDIR}",
                  "@VTKINCDIR@":"${VTKINCDIR}"},SUBSTFILESUFFIX=".pc")

#-------------------adding everyting to the "all" and "library" target----------
build_env.Alias("all",[temp_shared_library,
                       shared_library,shared_library_link,shared_library_so,
                       static_library,pkg_config_file])
build_env.Alias("library",[temp_shared_library,
                           shared_library,shared_library_link,shared_library_so,
                           static_library,pkg_config_file])

#---------------------installation----------------------------------------------

#install libraries
shared_library_install = build_env.Install("${LIBDIR}",[shared_library])
static_library_install = build_env.Install("${LIBDIR}",[static_library])

#create links for the link and so name versions of the library
inst_path = path.dirname(str(shared_library_install[0]))
shared_library_link_install = build_env.Command(inst_path+"/${LIBLINKNAME}",shared_library_install,
                  "cd ${SOURCE.dir}; ln -sf ${SOURCE.file} ${TARGET.file}")
                  
shared_library_so_install = build_env.Command(inst_path+"/${LIBSONAME}",shared_library_install,
                  "cd ${SOURCE.dir}; ln -sf ${SOURCE.file} ${TARGET.file}")                

#install the package-config file
pkgc_inst = build_env.Install("${LIBDIR}/pkgconfig",[pkg_config_file])

#install the header files
incpniutils_inst = build_env.Install("${INCDIR}",Glob("*.hpp"))

#add all installation targets to the global "install" target
build_env.Alias("install",[shared_library_install,static_library_install,
                           incpniutils_inst,pkgc_inst,
                           shared_library_link_install,
                           shared_library_so_install])



